# Archives Configuration

# Site
title: Archives
subtitle: ""
description: "A web archive"
keywords: "archive, web"
author: Yuba Technology, all Archives contributors and You
language: en-US

# URL
# Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/repo-name'
# Use `auto` will auto detect the url of your site in GitHub Pages.
url: auto
