name: Release notes

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.repository == 'Yuba-Technology/Archives'
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.BG_TOKEN }}
